
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-02
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - mountPath: /data
              name: volume-01
      volumes:
        - name: volume-01
          persistentVolumeClaim:
            claimName: pvc-01

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-01
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
