
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-1
  labels:
    app: front-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-1
  template:
    metadata:
      labels:
        app: front-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name: nginx-conf-1
      volumes:
      - name: nginx-conf-1
        configMap:
          name: nginx-configmap-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-2
  labels:
    app: front-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-2
  template:
    metadata:
      labels:
        app: front-2
    spec:
      containers:
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name: nginx-conf-2
      volumes:
      - name: nginx-conf-2
        configMap:
          name: nginx-configmap-2

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-1
data:
  index.html:
     <!DOCTYPE html>
     <html>
     <h1>Version 1.0</h1>
     </html>

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-2
data:
  index.html:
     <!DOCTYPE html>
     <html>
     <h1>Version 2.0</h1>
     </html>

---

apiVersion: v1
kind: Service
metadata:
  name: front-1
  labels:
    app: front-1
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: front-1

---

apiVersion: v1
kind: Service
metadata:
  name: front-2
  labels:
    app: front-2
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: front-2

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-svc
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front-1
            port:
              name: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "Version"
    nginx.ingress.kubernetes.io/canary-by-header-value: "2"
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: front-2
            port:
              name: http
