
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-02
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apps
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
          - mountPath: /log
            name: volume-01
      volumes:
        - name: volume-01
          hostPath:
            path: /var/log/syslog
            type: File
