
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-01
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx_multitool
  template:
    metadata:
      labels:
        app: nginx_multitool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        envFrom:
          - configMapRef:
              name: mt-configmap
        ports:
        - containerPort: 1180
          name: mt-http
        - containerPort: 11443
          name: mt-https
      - name: nginx
        image: nginx:1.20
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mt-configmap
data:
  HTTP_PORT: "1180"
  HTTPS_PORT: "11443"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html:
     <!DOCTYPE html>
     <html>
     <head>
     <title>Welcome to Netology!</title>
     <body>
     <h1>Welcome to Netology!</h1>
     </html>

